p8105\_hw3\_ws2646
================
Weize Sun
10/20/2021

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.4     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

## Problem 1

``` r
library(p8105.datasets)
data("instacart")
```

### Short discription of the dataset

This dataset contains 1384617 rows of observations and 15 columns of
variables. The structure is, each row represents one order of one
product by one user from an online grocery store “Instacart”. The 15
variables are order\_id, product\_id, add\_to\_cart\_order, reordered,
user\_id, eval\_set, order\_number, order\_dow, order\_hour\_of\_day,
days\_since\_prior\_order, product\_name, aisle\_id, department\_id,
aisle, department .

### Describing some key variables

``` r
mean(pull(instacart, reordered))
```

    ## [1] 0.5985944

``` r
names(sort(table(pull(instacart, order_hour_of_day)), decreasing = TRUE))[1]
```

    ## [1] "14"

``` r
mean(pull(instacart, days_since_prior_order))
```

    ## [1] 17.06613

``` r
names(sort(table(pull(instacart, product_name)), decreasing = TRUE))[1]
```

    ## [1] "Banana"

I found there are 4 variables are important.

The first one is `reordered`, which represents if the order has been
ordered or not.

The mean of `reordered` is 0.5985944, which means about 59.86% of the
orders has been reordered.

The second one is `order_hour_of_day`, which shows the hour of a day
when a user placed that order.

Most of the users placed order in 14, which is 2 pm.

The third one is `days_since_prior_order`, which means after how many
days the users reordered.

The mean of `days_since_prior_order` is 17.06613, which means users
often reordered after about 17 days.

The fourth one is `product_name`, which shows the name of a product.

Banana has been the most product the users ordered.
